ui.new_label("LUA", "B", "Music Kits")

function slot2()
	if entity.get_local_player() ~= nil and entity.get_prop(entity.get_player_resource(), "m_nMusicID", entity.get_local_player()) ~= (ui.get(uv0) == 0 and 1 or slot1 + 2) then
		entity.set_prop(entity.get_player_resource(), "m_nMusicID", slot2, slot0)
	end
end

ui.set_callback(ui.new_listbox("LUA", "B", "Music Kits", {
	"Default",
	nil,
	"Crimson Assault",
	"Sharpened",
	"Insurgency",
	"A*D*8",
	"High Noon",
	"Death's Head Demolition",
	"Desert Fire",
	"LNOE",
	"Metal",
	"All I Want for Christmas",
	"IsoRhythm",
	"For No Mankind",
	"Hotline Miami",
	"Total Domination",
	"The Talos Principle",
	"Battlepack",
	"MOLOTOV",
	"Uber Blasto Phone",
	"Hazardous Environments",
	"Headshot",
	"The 8-Bit Kit",
	"I Am",
	"Diamonds",
	"Invasion!",
	"Lion's Mouth",
	"Sponge Fingerz",
	"Disgusting",
	"Java Havana Funkaloo",
	"Moments CSGO",
	"Aggressive",
	"The Good Youth",
	"FREE",
	"Life's Not Out To Get You",
	"Backbone",
	"GLA",
	"III-Arena",
	"EZ4ENCE",
	"The Master Chief Collection",
	"Scar",
	"Anti Citizen",
	"Bachram",
	"Gunman Taco Truck",
	"Eye of the Dragon",
	"M.U.D.D. FORCE",
	"Neo Noir",
	"Bodacious",
	"Drifter",
	"All for Dust",
	"Hades Music Kit",
	"The Lowlife Pack",
	"CHAIN$AW.LXADXUT.",
	"Mocha Petal",
	"~Yellow Magic~",
	"Vici",
	"Astro Bellum",
	"Work Hard, Play Hard",
	"KOLIBRI",
	"u mad!",
	"Flashbang Dance",
	"Heading for the Source",
	"Void",
	"Shooters",
	"dashstar*",
	"Gothic Luxury",
	"Lock Me Up",
	"花脸 Hua Lian (Painted Face)",
	"ULTIMATE"
}), slot2)
client.set_event_callback("round_start", slot2)
